<?php
/** kavalogin.module - KAVA Login: adds CiviCRM <-> CAS login integration **/

/**
 * User insert hook. Runs after CAS, but before CiviCRM.
 * We're creating the UFMatch manually here before CiviCRM starts synchronizing user data.
 */
function kavalogin_user_insert(&$edit, $account, $category) {

  return KAVALoginHandler::getInstance()->match($account);
}

/**
 * User login hook. Runs after CAS (so we don't need cas_user_alter, etc), but before CiviCRM.
 * Check if a UFMatch exists and if not, if we can add one now.
 */
function kavalogin_user_login(&$edit, $account, $category) {

  return KAVALoginHandler::getInstance()->match($account);
}
